### ISSUE TITLE
Reference not found from Number of Commits

### ISSUE THREAD

**Issue by olivernybroe** [talos-systems/conform#184] opened 2020-11-13 10:52 UTC
So I am trying to setup conform and I keep getting this error when running it.

I am right now in a branch from our default branch, and I have the full git history locally
![image](https://user-images.githubusercontent.com/5870441/99064241-f8447680-25a5-11eb-8e3a-7c9fbd8fa66e.png)

**Comment by andrewrynhard** [comment] 2020-11-13 19:47
@olivernybroe Are you able to provide a way for me to reproduce?

**Comment by olivernybroe** [comment] 2020-11-13 20:04
@andrewrynhard hmm, I'll try and make a branch for reproducing it here next week 👍

**Comment by olivernybroe** [comment] 2020-11-16 08:24
@andrewrynhard Alright, so the issue seems to not have the default branch named `master`. 

I cloned this repo and reproduced it here on my main branch https://github.com/olivernybroe/conform

**Comment by andrewrynhard** [comment] 2020-11-16 08:48
Ah. Ok. I can look into getting support for `main`.

**Comment by olivernybroe** [comment] 2020-11-16 09:42
@andrewrynhard awesome, yeah so it's basically a general issue related to the branch not pointing on a branch named `master` 👍 

In our workplace we for some reason have the default branch named `develop` 🤣

**Comment by andrewrynhard** [comment] 2020-11-16 20:28
@olivernybroe looks like we have support for specifying the branch... please try passing in `--commit-ref=develop` (or `main`).

**Comment by olivernybroe** [comment] 2020-11-17 07:00
@andrewrynhard Alright cool that works, am I misunderstanding or we cannot set this via config file right?

**Comment by andrewrynhard** [comment] 2020-11-17 18:02
Doesn't look like it. But that isn't a bad idea.

**Comment by andrewrynhard** [comment] 2020-11-18 21:20
@olivernybroe I am going to close this, and create an issue to note the config changes.

**Closed by andrewrynhard** 2020-11-18 21:20 UTC
